# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852cc067884b9f0c4a5d0bd41cae32b6ab381026590487ca8ea97898982e08209dce0242fc20cdd84d70a8754f2992e21934820d2eaa19ae2a39ab508c8a2f48

test:
  secret_key_base: 54a0a82697bafa1eb02de95f675208e589f5e3faed1e7120365fc42c9f67972dd4327dc3f3631414f30ced1cf90d19dbe9cc3a49f5603ea2544e35b68298df2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
